#!/bin/sh
# Generated by stop-bots {VERSION}. Not executed automatically — review, then run
# with: sh <this file>
#
# Replaces the STOP-BOTS chain in one step with iptables-restore --noflush,
# then adds the jumps into it from INPUT, FORWARD and DOCKER-USER.
# Existing rules in those chains, all other chains, and every chain
# policy are left alone. IPv6 rules get the same chain in ip6tables.
# 4 IPv4 rule(s), 1 IPv6 rule(s).
set -e

iptables-restore -w --noflush <<'STOP_BOTS_IPV4'
*filter
:STOP-BOTS - [0:0]
-A STOP-BOTS -m state --state ESTABLISHED,RELATED -j ACCEPT
-A STOP-BOTS -i lo -j ACCEPT
-A STOP-BOTS -s 203.0.113.7 -j ACCEPT
-A STOP-BOTS -s 198.51.100.0/24 -j DROP
-A STOP-BOTS -s 192.0.2.9 -p tcp --dport 22 -j DROP
-A STOP-BOTS -s 192.0.2.77 -j DROP
COMMIT
STOP_BOTS_IPV4
if ! iptables -w -C INPUT -j STOP-BOTS 2>/dev/null; then
    iptables -w -I INPUT -j STOP-BOTS
fi
if ! iptables -w -C FORWARD -j STOP-BOTS 2>/dev/null; then
    iptables -w -I FORWARD -j STOP-BOTS
fi
if iptables -w -L DOCKER-USER -n >/dev/null 2>&1; then
    if ! iptables -w -C DOCKER-USER -j STOP-BOTS 2>/dev/null; then
        iptables -w -I DOCKER-USER -j STOP-BOTS
    fi
fi

if ip6tables -w -L INPUT -n >/dev/null 2>&1; then
ip6tables-restore -w --noflush <<'STOP_BOTS_IPV6'
*filter
:STOP-BOTS - [0:0]
-A STOP-BOTS -m state --state ESTABLISHED,RELATED -j ACCEPT
-A STOP-BOTS -i lo -j ACCEPT
-A STOP-BOTS -s 2001:db8::/32 -j DROP
COMMIT
STOP_BOTS_IPV6
    if ! ip6tables -w -C INPUT -j STOP-BOTS 2>/dev/null; then
        ip6tables -w -I INPUT -j STOP-BOTS
    fi
    if ! ip6tables -w -C FORWARD -j STOP-BOTS 2>/dev/null; then
        ip6tables -w -I FORWARD -j STOP-BOTS
    fi
    if ip6tables -w -L DOCKER-USER -n >/dev/null 2>&1; then
        if ! ip6tables -w -C DOCKER-USER -j STOP-BOTS 2>/dev/null; then
            ip6tables -w -I DOCKER-USER -j STOP-BOTS
        fi
    fi
else
    echo "stop-bots: ip6tables cannot be used on this host, so 1 IPv6 rule(s) were not applied" >&2
    exit 1
fi
