#!/bin/sh
# Generated by stop-bots. Not executed automatically — review, then run
# with: sh <this file>
#
# Only ever touches the dedicated STOP-BOTS chain: existing rules, other
# chains and policies are left alone.
set -e

if ! iptables -L STOP-BOTS -n >/dev/null 2>&1; then
    iptables -N STOP-BOTS
fi
iptables -F STOP-BOTS
if ! iptables -C INPUT -j STOP-BOTS 2>/dev/null; then
    iptables -I INPUT -j STOP-BOTS
fi
iptables -A STOP-BOTS -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A STOP-BOTS -i lo -j ACCEPT

iptables -A STOP-BOTS -s 203.0.113.7 -j ACCEPT
iptables -A STOP-BOTS -s 198.51.100.0/24 -j DROP
iptables -A STOP-BOTS -s 192.0.2.9 -p tcp --dport 22 -j DROP
# skipped (IPv6, not supported by iptables): 2001:db8::/32 — use nftables instead
