/*  This file is part of the stop-bots project.
 *
 *  Copyright (C) 2026 Marko Ivankovic
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//! The one line every whole file stop-bots writes carries at the top:
//! `Generated by stop-bots <version>`.
//!
//! **Only in files stop-bots owns outright** — the `conf.d` files, the
//! generated `robots.txt`, the systemd units, the firewall scripts. Never
//! inside the `# BEGIN stop-bots` block injected into an operator's own
//! site file, and never in the markers themselves:
//!
//! - The markers are how every past and future version finds its own
//!   block. A version inside one would make each release's marker a
//!   different string, and the next release would no longer recognise the
//!   block the previous one wrote — it would add a second one beside it.
//! - The site block is compared as rendered text to decide whether a site
//!   is `STALE` (`nginx::site_apply_status`). A version inside it would
//!   make every site on every host stale after every upgrade, when nothing
//!   about what it blocks had changed.
//!
//! A whole file has the second problem too, wherever its text is compared
//! rather than just rewritten: [`same_but_for_the_version`] is that
//! comparison.

/// The version this binary writes into a header.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// What every header starts with, version aside. Also how
/// [`same_but_for_the_version`] finds the line.
const GENERATED_BY: &str = "Generated by stop-bots";

/// `Generated by stop-bots <version>`, without a comment leader: each file
/// puts its own in front (`#` in all of them so far).
pub fn generated_by() -> String {
    format!("{GENERATED_BY} {VERSION}")
}

/// Whether `a` and `b` are the same generated file, ignoring which version
/// wrote the header.
///
/// For the places that decide whether a whole file is current by comparing
/// its text — the trust file is one, because every site that reads it is
/// `STALE` until it matches. Without this, the first upgrade after a
/// version started writing its number would flag every such site, and so
/// would every upgrade after it.
///
/// A header line is a comment line containing `Generated by stop-bots`,
/// with or without a version after it: files written before 0.1 carried
/// the same line without one, and must read as current too.
pub fn same_but_for_the_version(a: &str, b: &str) -> bool {
    // The trailing newline is part of the file, and `lines` hides it.
    a.ends_with('\n') == b.ends_with('\n') && without_header(a).eq(without_header(b))
}

fn without_header(text: &str) -> impl Iterator<Item = &str> {
    text.lines().filter(|line| !is_header_line(line))
}

fn is_header_line(line: &str) -> bool {
    let line = line.trim_start();
    line.starts_with('#') && line.contains(GENERATED_BY)
}

/// The version a header names, if `text` has one: `Some("0.1.0")` for
/// `# Generated by stop-bots 0.1.0. Edits will be overwritten.`.
///
/// `None` for a file written before headers carried a version.
pub fn version_in(text: &str) -> Option<&str> {
    text.lines()
        .filter(|line| is_header_line(line))
        .find_map(|line| {
            let rest = &line[line.find(GENERATED_BY)? + GENERATED_BY.len()..];
            let word = rest.strip_prefix(' ')?.split_whitespace().next()?;
            // `0.1.0.` at the end of a sentence, `0.1.0,` in a clause.
            let word = word.trim_end_matches(['.', ',', ';', ':', ')']);
            word.starts_with(|c: char| c.is_ascii_digit())
                .then_some(word)
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_header_names_this_version() {
        assert_eq!(
            generated_by(),
            format!("Generated by stop-bots {}", env!("CARGO_PKG_VERSION"))
        );
    }

    /// The comparison that keeps an upgrade from marking every site
    /// stale: only the header differs, whichever versions wrote it.
    #[test]
    fn two_versions_of_the_same_file_compare_equal() {
        let old = "# Generated by stop-bots. Edits will be overwritten.\ngeo $x {\n}\n";
        let new = "# Generated by stop-bots 0.1.0. Edits will be overwritten.\ngeo $x {\n}\n";
        let newer = "# Generated by stop-bots 0.2.0. Edits will be overwritten.\ngeo $x {\n}\n";
        for (a, b) in [(old, new), (new, newer), (old, newer)] {
            assert!(same_but_for_the_version(a, b), "{a:?} vs {b:?}");
        }
    }

    #[test]
    fn a_difference_outside_the_header_still_counts() {
        for (a, b, what) in [
            (
                "# Generated by stop-bots 0.1.0.\ngeo $x {\n}\n",
                "# Generated by stop-bots 0.1.0.\ngeo $y {\n}\n",
                "the body",
            ),
            (
                "# Generated by stop-bots 0.1.0.\ngeo $x {\n}\n",
                "# Generated by stop-bots 0.1.0.\ngeo $x {\n}",
                "the trailing newline",
            ),
            (
                "# Generated by stop-bots 0.1.0.\n# a comment\n",
                "# Generated by stop-bots 0.1.0.\n# another comment\n",
                "another comment line",
            ),
        ] {
            assert!(!same_but_for_the_version(a, b), "{what} was ignored");
        }
    }

    #[test]
    fn the_version_is_read_back_from_a_header() {
        for (text, expected) in [
            (
                "# Generated by stop-bots 0.1.0. Edits will be overwritten.\n",
                Some("0.1.0"),
            ),
            (
                "#!/bin/sh\n# Generated by stop-bots 0.1.0-rc.1. Not executed\n",
                Some("0.1.0-rc.1"),
            ),
            (
                "# Generated by stop-bots 0.2.0, with `install web`.\n",
                Some("0.2.0"),
            ),
            (
                "# Generated by stop-bots. Edits will be overwritten.\n",
                None,
            ),
            ("server {\n}\n", None),
        ] {
            assert_eq!(version_in(text), expected, "{text:?}");
        }
    }
}
