/*  This file is part of the stop-bots project.
 *
 *  Copyright (C) 2026 Marko Ivankovic
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//! Renders [`FirewallRule`]s into a shell script of plain `iptables`
//! commands.
//!
//! Deliberately *not* an `iptables-save`/`iptables-restore` dump: restoring a
//! full `*filter` table (as `iptables-restore` does) replaces the entire
//! table, including chain policies and any unrelated rules an admin already
//! has (e.g. their SSH allow rule) — silently, if they just pipe our output
//! in. Instead this renders individually-additive `iptables` invocations that
//! only ever touch our own `STOP-BOTS` chain, safe to run alongside whatever
//! else is already configured. This module never executes `iptables`
//! itself — see [`render`] for what gets written, applying it is a manual
//! step for the admin.
//!
//! `iptables` is IPv4-only — feeding it an IPv6 address fails at runtime
//! (`host/network ... not found`), which combined with `set -e` would abort
//! the script partway through, having applied only some rules. So IPv6
//! rules are skipped here (left as a comment) rather than emitted broken;
//! use [`crate::nftables`] for IPv6, which handles both families in one
//! table.

use crate::db::{FirewallAction, FirewallRule};

const CHAIN: &str = "STOP-BOTS";

fn action_word(action: FirewallAction) -> &'static str {
    match action {
        FirewallAction::Allow => "ACCEPT",
        FirewallAction::Block => "DROP",
        FirewallAction::Reject => "REJECT",
    }
}

fn is_ipv6(address: &str) -> bool {
    address.contains(':')
}

/// Renders `rules` (skipping disabled ones) into an idempotent `iptables`
/// shell script: safe to run repeatedly, and safe to run alongside any other
/// firewall rules already on the system.
///
/// IPv6 rules are skipped (see module docs); ports are rendered as
/// `-p tcp --dport <port>` — there's no protocol field on [`FirewallRule`]
/// yet, so UDP-specific rules aren't representable either (see TODO.md).
pub fn render(rules: &[FirewallRule]) -> String {
    let mut out = String::new();
    out.push_str("#!/bin/sh\n");
    out.push_str("# Generated by stop-bots. Not executed automatically — review, then run\n");
    out.push_str("# with: sh <this file>\n");
    out.push_str("#\n");
    out.push_str(&format!(
        "# Only ever touches the dedicated {CHAIN} chain: existing rules, other\n"
    ));
    out.push_str("# chains and policies are left alone.\n");
    out.push_str("set -e\n\n");

    out.push_str(&format!(
        "if ! iptables -L {CHAIN} -n >/dev/null 2>&1; then\n"
    ));
    out.push_str(&format!("    iptables -N {CHAIN}\n"));
    out.push_str("fi\n");
    out.push_str(&format!("iptables -F {CHAIN}\n"));
    out.push_str(&format!(
        "if ! iptables -C INPUT -j {CHAIN} 2>/dev/null; then\n"
    ));
    out.push_str(&format!("    iptables -I INPUT -j {CHAIN}\n"));
    out.push_str("fi\n");

    let enabled: Vec<&FirewallRule> = rules.iter().filter(|r| r.enabled).collect();
    if !enabled.is_empty() {
        out.push('\n');
    }
    for rule in enabled {
        if is_ipv6(&rule.address) {
            out.push_str(&format!(
                "# skipped (IPv6, not supported by iptables): {} — use nftables instead\n",
                rule.address
            ));
            continue;
        }
        out.push_str("iptables -A ");
        out.push_str(CHAIN);
        out.push_str(" -s ");
        out.push_str(&rule.address);
        if let Some(port) = rule.port {
            out.push_str(&format!(" -p tcp --dport {port}"));
        }
        out.push_str(" -j ");
        out.push_str(action_word(rule.action));
        out.push('\n');
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::NewFirewallRule;
    use serde::Deserialize;

    #[derive(Deserialize)]
    struct JsonRule {
        address: String,
        port: Option<u16>,
        action: String,
        enabled: bool,
    }

    fn rules_from_fixture(json: &str) -> Vec<FirewallRule> {
        let raw: Vec<JsonRule> = serde_json::from_str(json).unwrap();
        raw.into_iter()
            .enumerate()
            .map(|(i, r)| FirewallRule {
                id: i as i64,
                address: r.address,
                port: r.port,
                action: FirewallAction::parse(&r.action).unwrap(),
                enabled: r.enabled,
            })
            .collect()
    }

    const RULES_JSON: &str = include_str!("../tests/fixtures/iptables/rules.json");
    const BASIC_RULES: &str = include_str!("../tests/fixtures/iptables/basic_rules.txt");

    #[test]
    fn render_never_touches_other_chains_or_policies() {
        let rendered = render(&[]);
        assert!(!rendered.contains("INPUT DROP"));
        assert!(!rendered.contains("FORWARD"));
        assert!(!rendered.contains("OUTPUT"));
        assert!(!rendered.contains("*filter"));
        assert!(!rendered.contains("COMMIT"));
        assert!(!rendered.to_lowercase().contains("flush ruleset"));
    }

    #[test]
    fn render_empty_rules_still_sets_up_chain_and_jump() {
        let rendered = render(&[]);
        assert!(rendered.contains(&format!("iptables -N {CHAIN}")));
        assert!(rendered.contains(&format!("iptables -F {CHAIN}")));
        assert!(rendered.contains(&format!("iptables -I INPUT -j {CHAIN}")));
        assert!(!rendered.contains("-A STOP-BOTS -s"));
    }

    #[test]
    fn render_is_idempotent_via_guarded_chain_creation_and_jump() {
        let rendered = render(&[]);
        // Chain creation and the INPUT jump are both guarded so re-running
        // the script never duplicates the jump rule or errors on an
        // already-existing chain.
        assert!(rendered.contains("if ! iptables -L STOP-BOTS -n"));
        assert!(rendered.contains("if ! iptables -C INPUT -j STOP-BOTS"));
    }

    #[test]
    fn render_matches_fixture_rule_lines_from_json_input() {
        let rules = rules_from_fixture(RULES_JSON);
        let rendered = render(&rules);

        // These lines come straight from tests/fixtures/iptables/rules.json,
        // rendered the same way tests/fixtures/iptables/basic_rules.txt shows
        // hand-written stop-bots rules being expressed.
        assert!(rendered.contains("-A STOP-BOTS -s 1.2.3.4 -j DROP"));
        assert!(BASIC_RULES.contains("-A STOP-BOTS -s 1.2.3.4 -j DROP"));

        assert!(rendered.contains("-A STOP-BOTS -s 5.6.7.0/24 -j DROP"));
        assert!(BASIC_RULES.contains("-A STOP-BOTS -s 5.6.7.0/24 -j DROP"));

        assert!(rendered.contains("-A STOP-BOTS -s 8.9.10.11 -p tcp --dport 80 -j DROP"));
        assert!(BASIC_RULES.contains("-A STOP-BOTS -s 8.9.10.11 -p tcp --dport 80 -j DROP"));

        assert!(rendered.contains("-A STOP-BOTS -s 12.13.14.15 -j REJECT"));
        assert!(rendered.contains("-A STOP-BOTS -s 66.249.64.0/19 -j ACCEPT"));
    }

    #[test]
    fn render_skips_disabled_rules() {
        let rules = rules_from_fixture(RULES_JSON);
        let rendered = render(&rules);
        // rule-6 in the fixture (192.168.1.100) is disabled.
        assert!(!rendered.contains("192.168.1.100"));
    }

    #[test]
    fn render_skips_ipv6_addresses_instead_of_emitting_a_broken_rule() {
        // `iptables` is IPv4-only: an `-s 2001:db8::1` rule would error at
        // apply time ("host/network ... not found"), and with `set -e` that
        // aborts the whole script partway through. So IPv6 rules must never
        // appear as an `iptables -A ...` line — they're left as a comment.
        let rules = vec![FirewallRule {
            id: 1,
            address: "2001:db8::1".to_string(),
            port: None,
            action: FirewallAction::Block,
            enabled: true,
        }];
        let rendered = render(&rules);
        assert!(!rendered.contains("iptables -A STOP-BOTS -s 2001:db8::1"));
        assert!(rendered.contains("2001:db8::1"));
    }

    #[test]
    fn add_firewall_rule_then_render_round_trips() {
        let db = crate::db::Db::open_in_memory().unwrap();
        db.add_firewall_rule(&NewFirewallRule {
            address: "203.0.113.7".to_string(),
            port: Some(443),
            action: FirewallAction::Block,
        })
        .unwrap();

        let rules = db.list_firewall_rules().unwrap();
        let rendered = render(&rules);
        assert!(rendered.contains("-A STOP-BOTS -s 203.0.113.7 -p tcp --dport 443 -j DROP"));
    }
}
