/*  This file is part of the stop-bots project.
 *
 *  Copyright (C) 2026 Marko Ivankovic
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//! Renders [`FirewallRule`]s into a shell script of plain `iptables`
//! commands.
//!
//! Deliberately *not* an `iptables-save`/`iptables-restore` dump: restoring a
//! full `*filter` table (as `iptables-restore` does) replaces the entire
//! table, including chain policies and any unrelated rules an admin already
//! has (e.g. their SSH allow rule) — silently, if they just pipe our output
//! in. Instead this renders individually-additive `iptables` invocations that
//! only ever touch our own `STOP-BOTS` chain, safe to run alongside whatever
//! else is already configured. This module never executes `iptables`
//! itself — see [`render`] for what gets written, applying it is a manual
//! step for the admin.
//!
//! `iptables` is IPv4-only — feeding it an IPv6 address fails at runtime
//! (`host/network ... not found`), which combined with `set -e` would abort
//! the script partway through, having applied only some rules. So IPv6
//! rules are skipped here (left as a comment) rather than emitted broken;
//! use [`crate::nftables`] for IPv6, which handles both families in one
//! table.
//!
//! ## Default-deny (allowlist) mode
//!
//! For allowlist geo-blocking (block everything except selected countries),
//! [`crate::db::geo_firewall_rules`] generates a trailing `0.0.0.0/0` Block
//! rule. Unlike `nftables`, iptables cannot safely enforce this because:
//! 1. iptables is IPv4-only — the corresponding `::/0` IPv6 catch-all would
//!    be silently skipped, leaving IPv6 traffic completely unblocked.
//! 2. Without explicit allow rules for established connections and loopback
//!    (which this module now adds), a `0.0.0.0/0` rule would block all existing
//!    connections and local traffic. We now add those safety rules (see
//!    [`render`]), but the IPv6 limitation remains — hence allowlist mode
//!    requires the nftables backend (enforced in `main.rs`).

use crate::db::{FirewallAction, FirewallRule};

const CHAIN: &str = "STOP-BOTS";

fn action_word(action: FirewallAction) -> &'static str {
    match action {
        FirewallAction::Allow => "ACCEPT",
        FirewallAction::Block => "DROP",
        FirewallAction::Reject => "REJECT",
    }
}

fn is_ipv6(address: &str) -> bool {
    address.contains(':')
}

/// Renders `rules` (skipping disabled ones) into an idempotent `iptables`
/// shell script: safe to run repeatedly, and safe to run alongside any other
/// firewall rules already on the system.
///
/// IPv6 rules are skipped (see module docs); ports are rendered as
/// `-p tcp --dport <port>` — there's no protocol field on [`FirewallRule`]
/// yet, so UDP-specific rules aren't representable either (see TODO.md).
///
/// The generated chain always includes explicit ACCEPT rules for established/
/// related connections and loopback traffic before any user rules, ensuring
/// that a trailing catch-all block rule (used in allowlist geo mode) won't
/// lock out existing connections or local traffic.
pub fn render(rules: &[FirewallRule]) -> String {
    let mut out = String::new();
    out.push_str("#!/bin/sh\n");
    out.push_str("# Generated by stop-bots. Not executed automatically — review, then run\n");
    out.push_str("# with: sh <this file>\n");
    out.push_str("#\n");
    out.push_str(&format!(
        "# Only ever touches the dedicated {CHAIN} chain, plus the jumps into it\n"
    ));
    out.push_str("# from INPUT, FORWARD and DOCKER-USER. Existing rules in those chains,\n");
    out.push_str("# all other chains, and every chain policy are left alone.\n");
    out.push_str("set -e\n\n");

    out.push_str(&format!(
        "if ! iptables -L {CHAIN} -n >/dev/null 2>&1; then\n"
    ));
    out.push_str(&format!("    iptables -N {CHAIN}\n"));
    out.push_str("fi\n");
    out.push_str(&format!("iptables -F {CHAIN}\n"));
    out.push_str(&format!(
        "if ! iptables -C INPUT -j {CHAIN} 2>/dev/null; then\n"
    ));
    out.push_str(&format!("    iptables -I INPUT -j {CHAIN}\n"));
    out.push_str("fi\n");

    // `INPUT` alone only covers services running on the host. Traffic for a
    // published container port is DNAT'd and then *forwarded*, so it never
    // reaches `INPUT` and an `INPUT`-only jump enforces nothing for it —
    // see the module docs in `crate::nftables` for the same reasoning.
    out.push_str(&format!(
        "if ! iptables -C FORWARD -j {CHAIN} 2>/dev/null; then\n"
    ));
    out.push_str(&format!("    iptables -I FORWARD -j {CHAIN}\n"));
    out.push_str("fi\n");

    // And again from `DOCKER-USER`, which exists only when Docker does.
    //
    // The `FORWARD` jump above is inserted at the top, so on its own it
    // would already run first. What it does not survive is another chain
    // reaching a verdict before it: Docker puts its own `-j DOCKER-USER`
    // at the head of `FORWARD` on every restart, and an `ACCEPT` an admin
    // has put in there is terminal for the whole `FORWARD` traversal. That
    // packet would then never reach our jump. `DOCKER-USER` is the hook
    // Docker documents for exactly this, so we take both: the rules are
    // idempotent and `DROP` is terminal, so being traversed twice costs a
    // second pass over a short chain and changes no verdict.
    out.push_str("if iptables -L DOCKER-USER -n >/dev/null 2>&1; then\n");
    out.push_str(&format!(
        "    if ! iptables -C DOCKER-USER -j {CHAIN} 2>/dev/null; then\n"
    ));
    out.push_str(&format!("        iptables -I DOCKER-USER -j {CHAIN}\n"));
    out.push_str("    fi\n");
    out.push_str("fi\n");

    // Safety first: always accept established/related connections and loopback.
    // This is critical for allowlist mode where a trailing 0.0.0.0/0 block rule
    // would otherwise lock out all existing connections and local traffic.
    // Note: iptables is IPv4-only, so we can't match IPv6 addresses or set an
    // IPv6 default policy — both reasons allowlist mode requires nftables.
    out.push_str(&format!(
        "iptables -A {CHAIN} -m state --state ESTABLISHED,RELATED -j ACCEPT\n"
    ));
    out.push_str(&format!("iptables -A {CHAIN} -i lo -j ACCEPT\n"));

    let enabled: Vec<&FirewallRule> = rules.iter().filter(|r| r.enabled).collect();
    if !enabled.is_empty() {
        out.push('\n');
    }
    for rule in enabled {
        // Defence in depth. `Db` refuses to store an address this would
        // reject, so reaching here means a row predating that check (or a
        // database edited by hand). The script is executable input — `sh`
        // for this backend — so an address that isn't one is dropped rather
        // than interpolated. `{:?}` in the note, not `{}`: an unvalidated
        // address can contain a newline, which would end the comment and
        // make the remainder of it a command.
        if !crate::db::is_valid_address(&rule.address) {
            out.push_str(&format!(
                "# skipped (not an IP address or CIDR range): {:?}\n",
                rule.address
            ));
            continue;
        }
        // What was validated is the trimmed form, so that is what goes in
        // the script: a trailing newline would end the command early and
        // make `-j DROP` a command of its own.
        let address = rule.address.trim();
        if is_ipv6(address) {
            out.push_str(&format!(
                "# skipped (IPv6, not supported by iptables): {address} — use nftables instead\n"
            ));
            continue;
        }
        out.push_str("iptables -A ");
        out.push_str(CHAIN);
        out.push_str(" -s ");
        out.push_str(address);
        if let Some(port) = rule.port {
            out.push_str(&format!(" -p tcp --dport {port}"));
        }
        out.push_str(" -j ");
        out.push_str(action_word(rule.action));
        out.push('\n');
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::NewFirewallRule;
    use crate::testing::{allow, block, block_port, disabled};
    use serde::Deserialize;

    #[derive(Deserialize)]
    struct JsonRule {
        address: String,
        port: Option<u16>,
        action: String,
        enabled: bool,
    }

    fn rules_from_fixture(json: &str) -> Vec<FirewallRule> {
        let raw: Vec<JsonRule> = serde_json::from_str(json).unwrap();
        raw.into_iter()
            .enumerate()
            .map(|(i, r)| FirewallRule {
                id: i as i64,
                address: r.address,
                port: r.port,
                action: FirewallAction::parse(&r.action).unwrap(),
                enabled: r.enabled,
                expires_at: None,
            })
            .collect()
    }

    const RULES_JSON: &str = include_str!("../tests/fixtures/iptables/rules.json");
    const BASIC_RULES: &str = include_str!("../tests/fixtures/iptables/basic_rules.txt");

    #[test]
    fn render_never_touches_other_chains_or_policies() {
        let rendered = render(&[]);
        // `-P` is the only way to change a policy, and a table-level
        // restore is the only way to replace rules wholesale. Neither
        // appears; `FORWARD` and `DOCKER-USER` now do, which is why this
        // no longer just greps for their names — see the test below for
        // what it is allowed to say about them.
        assert!(
            !rendered.contains("iptables -P"),
            "rendered was:\n{rendered}"
        );
        assert!(!rendered.contains("OUTPUT"), "rendered was:\n{rendered}");
        assert!(!rendered.contains("*filter"), "rendered was:\n{rendered}");
        assert!(!rendered.contains("COMMIT"), "rendered was:\n{rendered}");
        assert!(!rendered.to_lowercase().contains("flush ruleset"));
        // Ours is the only chain flushed. Flushing a chain we merely jump
        // from would throw away an admin's own rules.
        let flushed: Vec<&str> = rendered
            .lines()
            .filter(|line| line.contains("-F "))
            .collect();
        assert_eq!(
            flushed,
            vec![format!("iptables -F {CHAIN}")],
            "only {CHAIN} may be flushed, but rendered was:\n{rendered}"
        );
    }

    /// The change that made this backend reach containerised services, and
    /// the bound on how far it reaches into chains it does not own.
    ///
    /// A packet for a published container port is DNAT'd and forwarded, so
    /// an `INPUT`-only jump never sees it. Both other chains therefore get
    /// a jump — and a jump is *all* they get: every line naming one is a
    /// guarded `-C`/`-I` of our own chain, never a rule of its own.
    #[test]
    fn every_hop_into_our_chain_is_covered_and_nothing_else_is_added() {
        let rendered = render(&[block("1.2.3.4")]);

        for chain in ["INPUT", "FORWARD", "DOCKER-USER"] {
            assert!(
                rendered.contains(&format!("iptables -I {chain} -j {CHAIN}")),
                "{chain} should jump to {CHAIN}, but rendered was:\n{rendered}"
            );
            assert!(
                rendered.contains(&format!("iptables -C {chain} -j {CHAIN}")),
                "the {chain} jump should be guarded, but rendered was:\n{rendered}"
            );
        }

        // DOCKER-USER exists only where Docker does, so unlike the other
        // two its jump is additionally guarded on the chain being there.
        assert!(
            rendered.contains("if iptables -L DOCKER-USER -n >/dev/null 2>&1; then"),
            "the DOCKER-USER jump should be guarded on Docker being present, \
             but rendered was:\n{rendered}"
        );

        // Nothing but jumps. A rule added to a chain we don't own would
        // outlive our chain and could not be cleaned up by re-running.
        for line in rendered.lines() {
            let line = line.trim();
            if (line.contains("FORWARD") || line.contains("DOCKER-USER") || line.contains("INPUT"))
                && line.starts_with("iptables")
            {
                assert!(
                    line.ends_with(&format!("-j {CHAIN}")),
                    "a chain we do not own may only gain a jump to {CHAIN}, but got:\n{line}"
                );
            }
        }
    }

    #[test]
    fn render_empty_rules_still_sets_up_chain_and_jump() {
        let rendered = render(&[]);
        assert!(rendered.contains(&format!("iptables -N {CHAIN}")));
        assert!(rendered.contains(&format!("iptables -F {CHAIN}")));
        assert!(rendered.contains(&format!("iptables -I INPUT -j {CHAIN}")));
        assert!(
            !rendered.contains("-A STOP-BOTS -s"),
            "rendered was:\n{rendered}"
        );
        // Even with no user rules, we still have safety rules for established/related and loopback
        assert!(
            rendered.contains("state --state ESTABLISHED,RELATED"),
            "rendered was:\n{rendered}"
        );
        assert!(
            rendered.contains("-i lo -j ACCEPT"),
            "rendered was:\n{rendered}"
        );
    }

    #[test]
    fn render_is_idempotent_via_guarded_chain_creation_and_jump() {
        let rendered = render(&[]);
        // Chain creation and the INPUT jump are both guarded so re-running
        // the script never duplicates the jump rule or errors on an
        // already-existing chain.
        assert!(
            rendered.contains("if ! iptables -L STOP-BOTS -n"),
            "rendered was:\n{rendered}"
        );
        assert!(
            rendered.contains("if ! iptables -C INPUT -j STOP-BOTS"),
            "rendered was:\n{rendered}"
        );
    }

    #[test]
    fn render_matches_fixture_rule_lines_from_json_input() {
        let rules = rules_from_fixture(RULES_JSON);
        let rendered = render(&rules);

        // These lines come straight from tests/fixtures/iptables/rules.json,
        // rendered the same way tests/fixtures/iptables/basic_rules.txt shows
        // hand-written stop-bots rules being expressed.
        assert!(
            rendered.contains("-A STOP-BOTS -s 1.2.3.4 -j DROP"),
            "rendered was:\n{rendered}"
        );
        assert!(BASIC_RULES.contains("-A STOP-BOTS -s 1.2.3.4 -j DROP"));

        assert!(
            rendered.contains("-A STOP-BOTS -s 5.6.7.0/24 -j DROP"),
            "rendered was:\n{rendered}"
        );
        assert!(BASIC_RULES.contains("-A STOP-BOTS -s 5.6.7.0/24 -j DROP"));

        assert!(
            rendered.contains("-A STOP-BOTS -s 8.9.10.11 -p tcp --dport 80 -j DROP"),
            "rendered was:\n{rendered}"
        );
        assert!(BASIC_RULES.contains("-A STOP-BOTS -s 8.9.10.11 -p tcp --dport 80 -j DROP"));

        assert!(
            rendered.contains("-A STOP-BOTS -s 12.13.14.15 -j REJECT"),
            "rendered was:\n{rendered}"
        );
        assert!(
            rendered.contains("-A STOP-BOTS -s 66.249.64.0/19 -j ACCEPT"),
            "rendered was:\n{rendered}"
        );
    }

    #[test]
    fn render_skips_disabled_rules() {
        let rules = rules_from_fixture(RULES_JSON);
        let rendered = render(&rules);
        // rule-6 in the fixture (192.168.1.100) is disabled.
        assert!(
            !rendered.contains("192.168.1.100"),
            "rendered was:\n{rendered}"
        );
    }

    #[test]
    fn render_skips_ipv6_addresses_instead_of_emitting_a_broken_rule() {
        // `iptables` is IPv4-only: an `-s 2001:db8::1` rule would error at
        // apply time ("host/network ... not found"), and with `set -e` that
        // aborts the whole script partway through. So IPv6 rules must never
        // appear as an `iptables -A ...` line — they're left as a comment.
        let rules = vec![block("2001:db8::1")];
        let rendered = render(&rules);
        assert!(
            !rendered.contains("iptables -A STOP-BOTS -s 2001:db8::1"),
            "rendered was:\n{rendered}"
        );
        assert!(
            rendered.contains("2001:db8::1"),
            "rendered was:\n{rendered}"
        );
    }

    #[test]
    fn add_firewall_rule_then_render_round_trips() {
        let db = crate::db::Db::open_in_memory().unwrap();
        db.add_firewall_rule(&NewFirewallRule {
            address: "203.0.113.7".to_string(),
            port: Some(443),
            action: FirewallAction::Block,
        })
        .unwrap();

        let rules = db.list_firewall_rules().unwrap();
        let rendered = render(&rules);
        assert!(
            rendered.contains("-A STOP-BOTS -s 203.0.113.7 -p tcp --dport 443 -j DROP"),
            "rendered was:\n{rendered}"
        );
    }

    /// The same rule set as `nftables`' golden, rendered for iptables —
    /// which silently skips the IPv6 rule (see the module docs). The golden
    /// is the exact script to hand to `sh -n` / a real `iptables-restore`
    /// review on a machine that has one.
    #[test]
    fn rendered_script_matches_the_golden() {
        let rules = vec![
            allow("203.0.113.7"),
            block("198.51.100.0/24"),
            block_port("192.0.2.9", 22),
            block("2001:db8::/32"),
            disabled("10.0.0.1"),
        ];
        crate::golden::assert_golden("firewall.iptables.sh", &render(&rules));
    }
    /// The database now refuses such a row, so this can only come from a
    /// database written before that check existed — but the script is
    /// executable input, and the cost of checking again here is nothing.
    #[test]
    fn render_skips_an_address_that_is_not_one_rather_than_emitting_it() {
        let rendered = render(&[block("1.2.3.4/24; touch /tmp/pwned")]);

        let statements: Vec<&str> = rendered
            .lines()
            .filter(|line| !line.trim_start().starts_with('#') && !line.trim().is_empty())
            .collect();
        assert!(
            !statements.iter().any(|line| line.contains("touch")),
            "the payload reached a statement line:\n{rendered}"
        );
        assert!(
            rendered.contains("skipped (not an IP address or CIDR range)"),
            "rendered was:\n{rendered}"
        );
    }

    /// Validation trims, so an address with whitespace around it is valid
    /// — and must be rendered as what was validated. Untrimmed, a trailing
    /// newline ended the command early and made `-j DROP` a command of its
    /// own, which under `set -e` aborts the script partway through.
    #[test]
    fn an_address_is_rendered_trimmed() {
        let rendered = render(&[block(" 1.2.3.4\n"), block(" 2001:db8::1 ")]);

        assert!(
            rendered.contains(&format!("iptables -A {CHAIN} -s 1.2.3.4 -j DROP\n")),
            "rendered was:\n{rendered}"
        );
        assert!(
            rendered.contains("# skipped (IPv6, not supported by iptables): 2001:db8::1 —"),
            "rendered was:\n{rendered}"
        );
    }

    /// A newline in the address would end the `#` comment the skip note is
    /// written as, making the rest of it a statement — so the note escapes.
    #[test]
    fn the_skip_note_cannot_be_escaped_with_a_newline() {
        let rendered = render(&[block("1.2.3.4\nflush ruleset")]);

        let statements: Vec<&str> = rendered
            .lines()
            .filter(|line| !line.trim_start().starts_with('#') && !line.trim().is_empty())
            .collect();
        assert!(
            !statements.iter().any(|line| line.contains("flush")),
            "the payload escaped the comment:\n{rendered}"
        );
    }
}
