/*  This file is part of the stop-bots project.
 *
 *  Copyright (C) 2026 Marko Ivankovic
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//! Renders [`FirewallRule`]s into an `nft -f` script, scoped to our own
//! `inet stop_bots` table.
//!
//! Two things a typical hand-written nftables script (like the ones in
//! `tests/fixtures/nftables/`) gets away with, but that this generator
//! deliberately avoids:
//!
//! - `flush ruleset` wipes *every* table on the system, not just ours. We
//!   only ever reset our own table: `add table inet stop_bots` (a no-op if
//!   it already exists) followed by `delete table inet stop_bots` (now
//!   guaranteed to exist) then `add table inet stop_bots` again — leaving a
//!   guaranteed-fresh, empty table scoped to just us, with every other table
//!   on the system untouched. The chain and rules are then added fresh into
//!   it, so the whole script is safe to re-run without ever needing to know
//!   whether a previous run already created the base chain (re-declaring an
//!   existing hooked base chain via `add chain` is not reliably a no-op,
//!   unlike `add table`).
//! - `policy drop` on a chain hooked at `priority -1` on `input` makes that
//!   chain the de facto gatekeeper for *all* inbound traffic on the host:
//!   anything not explicitly accepted gets dropped, including ordinary
//!   traffic to the box. We use `policy accept` instead, so this chain only
//!   ever blocks the specific addresses it's told to.
//!
//! This module never executes `nft` itself — applying the generated script
//! is a manual step for the admin. Like the rest of this module, the
//! delete-then-recreate idempotency idiom hasn't been checked against a
//! real `nft` (not installed in this environment) — see TODO.md.

use crate::db::{FirewallAction, FirewallRule};

const TABLE: &str = "inet stop_bots";
const CHAIN: &str = "bot_block";

fn action_word(action: FirewallAction) -> &'static str {
    match action {
        FirewallAction::Allow => "accept",
        FirewallAction::Block => "drop",
        FirewallAction::Reject => "reject",
    }
}

fn is_ipv6(address: &str) -> bool {
    address.contains(':')
}

/// Renders `rules` (skipping disabled ones) into an idempotent `nft` script.
///
/// Ports are rendered as `tcp dport <port>`; there's no protocol field on
/// [`FirewallRule`] yet, so UDP-specific rules aren't representable (see
/// TODO.md).
pub fn render(rules: &[FirewallRule]) -> String {
    let mut out = String::new();
    out.push_str("#!/usr/sbin/nft -f\n");
    out.push_str("# Generated by stop-bots. Not executed automatically — review, then run\n");
    out.push_str("# with: nft -f <this file>\n");
    out.push_str("#\n");
    out.push_str("# Only touches our own \"inet stop_bots\" table (no `flush ruleset`) and\n");
    out.push_str("# uses \"policy accept\" so this chain can't become an implicit\n");
    out.push_str("# default-deny for all inbound traffic.\n\n");

    // Reset just our own table to a fresh, empty state (see module docs for
    // why this is the idempotent idiom rather than `flush chain`).
    out.push_str(&format!("add table {TABLE}\n"));
    out.push_str(&format!("delete table {TABLE}\n"));
    out.push_str(&format!("add table {TABLE}\n"));
    out.push_str(&format!(
        "add chain {TABLE} {CHAIN} {{ type filter hook input priority -1; policy accept; }}\n\n"
    ));

    out.push_str(&format!(
        "add rule {TABLE} {CHAIN} ct state established,related accept\n"
    ));
    out.push_str(&format!("add rule {TABLE} {CHAIN} iif lo accept\n"));

    let enabled: Vec<&FirewallRule> = rules.iter().filter(|r| r.enabled).collect();
    if !enabled.is_empty() {
        out.push('\n');
    }
    for rule in enabled {
        let family = if is_ipv6(&rule.address) { "ip6" } else { "ip" };
        out.push_str(&format!(
            "add rule {TABLE} {CHAIN} {family} saddr {}",
            rule.address
        ));
        if let Some(port) = rule.port {
            out.push_str(&format!(" tcp dport {port}"));
        }
        out.push_str(&format!(" {}\n", action_word(rule.action)));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::NewFirewallRule;
    use crate::testing::{allow, block, block_port, disabled};
    use serde::Deserialize;

    #[derive(Deserialize)]
    struct JsonRule {
        address: String,
        port: Option<u16>,
        action: String,
        enabled: bool,
    }

    fn rules_from_fixture(json: &str) -> Vec<FirewallRule> {
        let raw: Vec<JsonRule> = serde_json::from_str(json).unwrap();
        raw.into_iter()
            .enumerate()
            .map(|(i, r)| FirewallRule {
                id: i as i64,
                address: r.address,
                port: r.port,
                action: FirewallAction::parse(&r.action).unwrap(),
                enabled: r.enabled,
                expires_at: None,
            })
            .collect()
    }

    const RULES_JSON: &str = include_str!("../tests/fixtures/nftables/rules.json");

    #[test]
    fn render_never_flushes_the_whole_ruleset_or_drops_by_default() {
        let rendered = render(&[]);
        // Check actual statement lines, not the explanatory comment above
        // them (which mentions "flush ruleset" as the thing being avoided).
        let statements: Vec<&str> = rendered
            .lines()
            .filter(|line| !line.trim_start().starts_with('#'))
            .collect();
        assert!(!statements.iter().any(|line| line.trim() == "flush ruleset"));
        assert!(!statements.iter().any(|line| line.contains("policy drop")));
        assert!(
            rendered.contains("policy accept"),
            "rendered was:\n{rendered}"
        );
    }

    #[test]
    fn render_empty_rules_still_sets_up_table_and_chain() {
        let rendered = render(&[]);
        assert!(rendered.contains(&format!("add table {TABLE}")));
        assert!(rendered.contains(&format!("delete table {TABLE}")));
        assert!(rendered.contains(&format!("add chain {TABLE} {CHAIN}")));
        assert!(
            rendered.contains("ct state established,related accept"),
            "rendered was:\n{rendered}"
        );
        assert!(
            rendered.contains("iif lo accept"),
            "rendered was:\n{rendered}"
        );
        assert!(!rendered.contains("saddr"), "rendered was:\n{rendered}");
    }

    #[test]
    fn render_resets_only_its_own_table_for_idempotency() {
        let rendered = render(&[]);
        // `add table` (no-op if it exists) then `delete table` (now
        // guaranteed to exist) then `add table` again leaves a fresh, empty
        // table scoped to just "inet stop_bots" — safe to re-run, and never
        // a `flush ruleset` or a delete of a possibly-nonexistent table.
        let add_count = rendered.matches(&format!("add table {TABLE}")).count();
        assert_eq!(add_count, 2);
        assert_eq!(
            rendered.matches(&format!("delete table {TABLE}")).count(),
            1
        );
    }

    #[test]
    fn render_matches_fixture_rule_lines_from_json_input() {
        let rendered = render(&rules_from_fixture(RULES_JSON));

        // A table, so the cases read as a list of "this input shape
        // produces this line" rather than as six near-identical asserts —
        // and so a failure names which shape broke and prints the script,
        // instead of pointing at a line number and a bare `false`.
        let expected = [
            ("a bare IPv4 address", "ip saddr 1.2.3.4 drop"),
            ("an IPv4 CIDR", "ip saddr 5.6.7.0/24 drop"),
            ("IPv4 with a port", "ip saddr 8.9.10.11 tcp dport 80 drop"),
            ("the Reject action", "ip saddr 12.13.14.15 reject"),
            ("the Allow action", "ip saddr 66.249.64.0/19 accept"),
            (
                "IPv6 with a port",
                "ip6 saddr 2001:db8::1 tcp dport 443 drop",
            ),
        ];
        for (shape, line) in expected {
            let full = format!("add rule inet stop_bots bot_block {line}");
            assert!(
                rendered.contains(&full),
                "{shape} should render as {full:?}, but the script was:\n{rendered}"
            );
        }
    }

    #[test]
    fn render_skips_disabled_rules() {
        let mut rules = rules_from_fixture(RULES_JSON);
        rules[0].enabled = false;
        let rendered = render(&rules);
        assert!(!rendered.contains(&rules[0].address));
    }

    #[test]
    fn render_uses_ip6_saddr_for_ipv6_and_ip_saddr_for_ipv4() {
        let rules = vec![block("2001:db8:85a3::8a2e:370:7334/64"), block("10.0.0.1")];
        let rendered = render(&rules);
        assert!(
            rendered.contains("ip6 saddr 2001:db8:85a3::8a2e:370:7334/64 drop"),
            "rendered was:\n{rendered}"
        );
        assert!(
            rendered.contains("ip saddr 10.0.0.1 drop"),
            "rendered was:\n{rendered}"
        );
    }

    #[test]
    fn add_firewall_rule_then_render_round_trips() {
        let db = crate::db::Db::open_in_memory().unwrap();
        db.add_firewall_rule(&NewFirewallRule {
            address: "203.0.113.7".to_string(),
            port: Some(443),
            action: FirewallAction::Block,
        })
        .unwrap();

        let rules = db.list_firewall_rules().unwrap();
        let rendered = render(&rules);
        assert!(
            rendered.contains("ip saddr 203.0.113.7 tcp dport 443 drop"),
            "rendered was:\n{rendered}"
        );
    }

    /// A representative rule set, locked byte-for-byte. The golden file is
    /// also the exact script to hand to `nft -c -f` on a machine that has
    /// it — see `crate::golden`.
    #[test]
    fn rendered_script_matches_the_golden() {
        let rules = vec![
            allow("203.0.113.7"),
            block("198.51.100.0/24"),
            block_port("192.0.2.9", 22),
            block("2001:db8::/32"),
            // Disabled: must leave no trace in the script.
            disabled("10.0.0.1"),
        ];
        crate::golden::assert_golden("firewall.nft", &render(&rules));
    }

    /// Allowlist geo mode's shape: explicit Allows followed by the v4 and
    /// v6 catch-alls, strictly last.
    #[test]
    fn rendered_allowlist_script_matches_the_golden() {
        let rules = vec![allow("203.0.113.0/24"), block("0.0.0.0/0"), block("::/0")];
        crate::golden::assert_golden("firewall-allowlist.nft", &render(&rules));
    }
}
